[[language]]
name = "gren"
scope = "source.gren"
injection-regex = "gren"
file-types = ["gren"]
roots = ["gren.json"]
comment-tokens = "--"
block-comment-tokens = { start = "{-", end = "-}" }
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "gren"
source = { git = "https://github.com/MaeBrooks/tree-sitter-gren", rev = "76554f4f2339f5a24eed19c58f2079b51c694152" }
